export const mockLiveAttacks = [
  {
    id: "live-001",
    timestamp: "10:42:31",
    sourceIp: "185.12.44.21",
    country: "Germany",
    honeypot: "Dionaea",
    service: "FTP",
    eventType: "Authentication Attempt",
    status: "failed",
  },
  {
    id: "live-002",
    timestamp: "10:43:08",
    sourceIp: "45.88.12.7",
    country: "United States",
    honeypot: "Snare",
    service: "HTTP",
    eventType: "Web Request",
    status: "detected",
  },
  {
    id: "live-003",
    timestamp: "10:44:17",
    sourceIp: "91.204.18.63",
    country: "Russia",
    honeypot: "Cowrie",
    service: "SSH",
    eventType: "Login Attempt",
    status: "failed",
  },
  {
    id: "live-004",
    timestamp: "10:45:02",
    sourceIp: "103.77.14.8",
    country: "India",
    honeypot: "Cowrie",
    service: "SSH",
    eventType: "Command Attempt",
    status: "detected",
  },
];
